### ISSUE TITLE
Folder batch-processing cannot handle differently sized stacks

### ISSUE THREAD

**Issue by kjamartens** [HohlbeinLab/FTM2#4]
When running the folder-based batch processing on a folder containing TIFF stacks with sizes 1000,5000,1000 (alphabetically ordered), the output of all 3 files is 1000 frames, rather than 1000,5000,1000.

**Comment by DrNjitram** [comment]
What are the exact settings used and the sizes of the files? From the issue, I assume you process them separately. Do they share other attributes like bit-depth and frame size?

**Comment by kjamartens** [comment]
So I had three files (recorded from same microscope with same settings, so same bit-depth and x,y size). They are TIFF stacks with sizes: [512,512,1000], [512,512,5000], [512,512,1000] called "a","b","c" (for sake of argument, alphabetically they're ordered this way). I can process them individually without issues, but when I run the 'select folder and run', the output for all three files is [512,512,1000].

I have quickly tried to reproduce it with stacks sized [64,64,100] called "a.tif", [64,64,500] called "b.tif", and [64,64,100] called "c.tif", and I experience the same issue --> all three files turn out to be [64,64,100]. The 100 frames are the first 100 frames in "b".

**Comment by DrNjitram** [comment]
I have identified the issue, and it had to do with Java classes carrying over some values between runs due to instancing of classes. The version attached shouldn't have these issues. 

Can you try with the attached jar and see if it is fixed?
[FTM_2-0.10-SNAPSHOT.jar.zip](https://github.com/HohlbeinLab/FTM2/files/6735400/FTM_2-0.10-SNAPSHOT.jar.zip)

**Comment by kjamartens** [comment]
The issue seems to have been fixed correctly.

However, I have another issue (which already existed, but just noticed it now):
Trying to save images to an output directory which has a space in the name crashes the saving procedure (f.e. trying to save to file "C:/Space Here/Output/A.tif" results in the program trying to save to file "C:/Space/A.tif", which doesn't exist.

**Comment by DrNjitram** [comment]
This issue was due to incorrect handling of filepaths, and discarding incorrect tokens.
This is fixed by using quotes around the filepath in script, but the program now correctly checks this and tells you if an issue was found.
If the attached version works I will push the codechanges.
[FTM_2-0.10-SNAPSHOT.jar.zip](https://github.com/HohlbeinLab/FTM2/files/6786174/FTM_2-0.10-SNAPSHOT.jar.zip)
